# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Question.create(question_title: "Where a test question?", question_content: "A bird is an instrument working according to mathematical law, which instrument it is within the capacity of man to reproduce with all its movements.
#
# Thank God men cannot fly, and lay waste the sky as well as the earth.
#
# I suppose we shall soon travel by air-vessels; make air instead of sea voyages; and at length find our way to the Moon, in spite of the want of atmosphere.", question_author: "Jill Doe")
# Question.create(question_title: "When a test question?", question_content: "Soon shall thy arm, unconquer'd steam! afar. Drag the slow barge, or drive the rapid car; Or on wide-waving wings extended bear. The flying chariot through the field of air.
#
# Anyone who should see in the sky such a globe should be aware that, far from being an alarming phenomenon, it is only a machine made of taffetas or light canvas covered with paper, that cannot possibly cause any harm, and which will someday prove serviceable to the wants of society.
#
# At first we will only skim the surface of the earth like young starlings, but soon, emboldened by practice and experience, we will spring into the air with the impetuousness of the eagle, diverting ourselves by watching the childish behavior of the little men or awling miserably around on the earth below us.", question_author: "Jim Doe")
# Question.create(question_content: "The Art of Flying is but newly invented, 'twill improve by degrees, and in time grow perfect; then we may fly as far as the Moon.", question_title: "Why a test question?", question_author: "John Doe")
# Question.create(question_content: "When a prang seems inevitable, endeavor to strike the softest, cheapest object in the vicinity, as slowly and gently as possible.", question_title: "How a test question?", question_author: "Jane Doe")

Section.create(section_name: "Ruby")
Section.create(section_name: "JS")
Section.create(section_name: "CSS")
Section.create(section_name: "HTML")
User.create!([
  {email: "admin@admin.com", encrypted_password: "$2a$10$CzGzvUoXgk5HzyI4Q8rlXOjpEvPFU.3Q2WHIEw8EGoJzKmevgvp.S", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 12, current_sign_in_at: "2015-12-04 04:51:31", last_sign_in_at: "2015-12-02 06:31:56", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", admin: true}
])
Answer.create!([
  {answer_content: "Beard iPhone squid, keffiyeh trust fund waistcoat jean shorts XOXO chillwave chambray master cleanse austin PBR&B farm-to-table. Kinfolk viral sriracha master cleanse, seitan bushwick lo-fi crucifix meh occupy meditation yuccie health goth PBR&B 8-bit. Pour-over you probably haven't heard of them drinking vinegar cronut.", answer_author: "Locavore selvage", question_id: 1, vote: 0, star: false},
  {answer_content: "Banjo before they sold out beard, normcore hammock tattooed kickstarter schlitz intelligentsia lumbersexual dreamcatcher trust fund selvage. Cred try-hard chicharrones messenger bag.", answer_author: "Health goth", question_id: 1, vote: 0, star: false},
  {answer_content: "Kinfolk fingerstache kickstarter, hoodie lumbersexual cronut whatever forage trust fund literally iPhone occupy organic flannel. Polaroid raw denim health goth, quinoa distillery selfies.", answer_author: "literally vinyl", question_id: 4, vote: 0, star: false},
  {answer_content: "Hashtag lumbersexual taxidermy artisan, helvetica gastropub meditation chicharrones chia synth before they sold out knausgaard offal. Yuccie green juice tote bag YOLO cronut actually, kickstarter literally. Whatever mumblecore farm-to-table fixie, post-ironic echo park aesthetic blog gastropub chicharrones synth.", answer_author: "brooklyn schlitz", question_id: 2, vote: 0, star: false},
  {answer_content: "DIY waistcoat banh mi, master cleanse hella mlkshk gluten-free bushwick. Everyday carry franzen cronut lumbersexual hammock chicharrones offal. Biodiesel VHS ethical locavore, meditation etsy blue bottle narwhal you probably haven't heard of them vinyl beard skateboard cliche. Plaid health goth before they sold out small batch, retro mlkshk yuccie green juice. Fanny pack DIY dreamcatcher humblebrag neutra meggings, skateboard post-ironic distillery keffiyeh four dollar toast stumptown celiac you probably haven't heard of them seitan. Kinfolk fingerstache kickstarter, hoodie lumbersexual cronut whatever forage trust fund literally iPhone occupy organic flannel. Polaroid raw denim health goth, quinoa distillery selfies literally vinyl.\r\n\r\nBanjo before they sold out beard, normcore hammock tattooed kickstarter schlitz intelligentsia lumbersexual dreamcatcher trust fund selvage. Cred try-hard chicharrones messenger bag. Health goth pug retro sustainable, poutine cred gentrify VHS. Tousled neutra poutine bushwick narwhal, selvage mustache bespoke lo-fi artisan pop-up. Beard iPhone squid, keffiyeh trust fund waistcoat jean shorts XOXO chillwave chambray master cleanse austin PBR&B farm-to-table. Kinfolk viral sriracha master cleanse, seitan bushwick lo-fi crucifix meh occupy meditation yuccie health goth PBR&B 8-bit. Pour-over you probably haven't heard of them drinking vinegar cronut.", answer_author: "seitan", question_id: 4, vote: 3, star: false},
  {answer_content: "Selfies farm-to-table hashtag squid actually, DIY flexitarian raw denim truffaut brooklyn schlitz. Mixtape brooklyn etsy, art party cray direct trade tattooed. 3 wolf moon pour-over bushwick, celiac vice knausgaard next level yr direct trade kogi four loko offal pinterest vegan. Sartorial asymmetrical kitsch dreamcatcher deep v, chia pinterest everyday carry stumptown organic tumblr.", answer_author: "v austin", question_id: 2, vote: 4, star: false},
  {answer_content: "Asymmetrical craft beer typewriter irony etsy. Squid beard authentic shabby chic celiac. Chartreuse four loko YOLO pickled waistcoat umami. Intelligentsia scenester yuccie, microdosing drinking vinegar stumptown bicycle rights banjo pitchfork godard. Kale chips PBR&B fap chillwave cray. Brooklyn slow-carb YOLO tote bag, truffaut narwhal VHS retro hammock next level cardigan chicharrones pug aesthetic.", answer_author: "Banh mi", question_id: 2, vote: 1, star: false},
  {answer_content: "Literally asymmetrical leggings, irony art party intelligentsia quinoa kitsch. Locavore wayfarers plaid biodiesel +1, raw denim hoodie cardigan taxidermy viral heirloom vice irony. Literally intelligentsia bitters, microdosing try-hard gluten-free taxidermy post-ironic hella. Tattooed church-key hashtag hella actually, waistcoat tousled DIY heirloom fixie tote bag migas yr deep v austin. Ethical typewriter hashtag poutine health goth offal. Shoreditch paleo deep v, pabst waistcoat messenger bag keffiyeh. Bespoke dreamcatcher meh, tattooed tilde helvetica heirloom.", answer_author: "knausgaard", question_id: 2, vote: 0, star: false}
])
Question.create!([
  {question_content: "Lomo viral humblebrag pitchfork pabst iPhone. Art party ugh vinyl lomo disrupt blue bottle, +1 four loko forage swag. Food truck tattooed brunch pitchfork everyday carry, fap offal swag ethical hoodie fashion axe meggings vinyl art party wolf. Pug mumblecore pitchfork 90's freegan health goth. Tilde sriracha gluten-free williamsburg try-hard bespoke vice bitters, vinyl marfa pabst. Pug hammock narwhal, selfies 8-bit bushwick venmo freegan vinyl authentic truffaut microdosing celiac thundercats salvia. Asymmetrical meditation fashion axe pabst, brunch health goth single-origin coffee photo booth YOLO cray.", question_author: "Saadiq", question_title: "How can I add unlimited loops to this whole JS?", section_id: 2},
  {question_content: "Intelligentsia scenester yuccie, microdosing drinking vinegar stumptown bicycle rights banjo pitchfork godard.", question_author: "truffaut narwhal", question_title: "Rails with Bootstrap Tabs", section_id: 1},
  {question_content: "Tattooed church-key hashtag hella actually, waistcoat tousled DIY heirloom fixie tote bag migas yr deep v austin. Ethical typewriter hashtag poutine health goth offal. Shoreditch paleo deep v, pabst waistcoat messenger bag keffiyeh.", question_author: "Typewriter DIY", question_title: "Shoreditch plaid post-ironic, taxidermy trust fund cred occupy 90's migas?", section_id: 2},
  {question_content: "Heirloom flannel green juice umami semiotics. Ennui selvage cliche, yr artisan squid godard deep v kogi pabst shoreditch. Gastropub drinking vinegar cred, DIY artisan mustache roof party taxidermy stumptown kale chips helvetica. Seitan williamsburg shabby chic literally helvetica kombucha. Letterpress meditation whatever, kogi cold-pressed tilde gluten-free blue bottle yuccie 90's.", question_author: "Salvia blog", question_title: "Heirloom kale chips narwhal actually. Everyday carry pinterest bicycle rights?", section_id: 2},
  {question_content: "hella tilde cray venmo taxidermy. XOXO selvage vinyl, meditation seitan iPhone single-origin coffee fashion axe beard bicycle rights readymade. Quinoa poutine banjo truffaut, raw denim scenester tilde trust fund try-hard YOLO. Kickstarter mustache literally, helvetica shabby chic squid blue bottle deep v trust fund ramps. Portland mustache waistcoat tattooed, synth shoreditch fixie farm-to-table XOXO PBR&B. Fanny pack pop-up wayfarers, skateboard pabst twee polaroid selvage listicle. Fingerstache meggings ennui, fixie pork belly flannel migas four loko pickled PBR&B polaroid kickstarter kale chips waistcoat plaid.", question_author: "Tim Tam", question_title: "Hoodie roof party ennui four loko?", section_id: 3},
  {question_content: "Fingerstache meggings ennui, fixie pork belly flannel migas four loko pickled PBR&B polaroid kickstarter kale chips waistcoat plaid.\r\n\r\nHelvetica microdosing truffaut pabst neutra. Mustache kale chips wolf pug, vinyl chambray meditation austin literally blue bottle fanny pack pour-over health goth godard beard. You probably haven't heard of them poutine venmo banjo, tattooed marfa craft beer microdosing bicycle rights locavore. Plaid bitters kombucha narwhal pabst hoodie. Cronut celiac chartreuse, DIY skateboard synth kickstarter tilde food truck salvia poutine dreamcatcher gastropub iPhone shabby chic. Plaid cred chia, deep v readymade neutra narwhal before they sold out church-key forage. Tofu messenger bag bespoke, tote bag gastropub echo park whatever ethical single-origin coffee street art.", question_author: "Mustache kale", question_title: "DIY skateboard gastropub iPhone ", section_id: 3},
  {question_content: "Fixie flannel before they sold out chambray, chicharrones marfa shabby chic biodiesel pickled raw denim. Photo booth franzen everyday carry flannel. Humblebrag cliche selvage, tousled actually selfies stumptown iPhone asymmetrical direct trade tattooed meh. 3 wolf moon yuccie hoodie semiotics, bitters +1 seitan. Food truck organic pabst, next level chartreuse synth yuccie gluten-free austin. Umami butcher tousled stumptown keytar leggings, cardigan readymade pickled. Meditation tote bag hoodie hashtag paleo.", question_author: "Tofu messenger", question_title: "Synth kickstarter tilde food truck salvia poutine dreamcatcher gastropub iPhone ", section_id: 3},
  {question_content: "Four loko banh mi chicharrones, yuccie everyday carry drinking vinegar four dollar toast portland vice keffiyeh sustainable retro. Franzen master cleanse cray, keytar bespoke chartreuse chia 90's tofu portland migas. Quinoa leggings blog drinking vinegar cray, slow-carb skateboard street art. Beard tofu meditation PBR&B kogi. XOXO pug kale chips umami, before they sold out tattooed godard offal normcore shoreditch mustache squid actually portland twee. Godard skateboard seitan, tousled pitchfork cronut letterpress. +1 synth single-origin coffee, master cleanse schlitz banh mi stumptown ennui poutine swag distillery.", question_author: "vice keffiyeh", question_title: "90's tofu portland migas", section_id: 4},
  {question_content: "DIY skateboard synth kickstarter tilde food truck salvia poutine dreamcatcher gastropub iPhone shabby chic. Plaid cred chia, deep v readymade neutra narwhal before they sold out church-key forage. Tofu messenger bag bespoke, tote bag gastropub echo park whatever ethical single-origin coffee street art.\r\n\r\nFixie flannel before they sold out chambray, chicharrones marfa shabby chic biodiesel pickled raw denim. Photo booth franzen everyday carry flannel. ", question_author: "level chartreuse", question_title: "Meditation tote bag?", section_id: 4},
  {question_content: "Irony fixie photo booth chicharrones chartreuse, knausgaard mustache paleo scenester asymmetrical selvage green juice. Skateboard chia disrupt post-ironic yuccie. Stumptown four dollar toast deep v craft beer tattooed organic. Umami williamsburg twee, health goth yuccie art party cronut. Hammock gastropub franzen meditation crucifix disrupt. Godard selvage VHS tattooed thundercats fap, heirloom gastropub celiac microdosing. Green juice squid food truck austin photo booth brunch bushwick pour-over, pickled pop-up mlkshk DIY next level.", question_author: "gitastic", question_title: "Multiple Swiper instances inside each loop", section_id: 1},
  {question_content: "Echo park 90's selvage, pug street art messenger bag kombucha. Asymmetrical twee blog fanny pack. Shoreditch plaid post-ironic, taxidermy trust fund cred occupy 90's migas. Quinoa wolf hammock hoodie.\r\n\r\n Typewriter DIY next level cold-pressed, etsy truffaut microdosing chambray austin before they sold out kombucha. Lomo YOLO XOXO, whatever cliche mixtape health goth lo-fi chicharrones yuccie fingerstache humblebrag viral ramps. Mumblecore craft beer godard, shabby chic pinterest meggings vinyl gluten-free yr hella helvetica messenger bag blue bottle cardigan.", question_author: "Asymmetrical", question_title: "Rails 4.2 Disable before_create for seeds", section_id: 1},
  {question_content: "Hoodie roof party ennui four loko, hella tilde cray venmo taxidermy. XOXO selvage vinyl, meditation seitan iPhone single-origin coffee fashion axe beard bicycle rights readymade. Quinoa poutine banjo truffaut, raw denim scenester tilde trust fund try-hard YOLO. Kickstarter mustache literally, helvetica shabby chic squid blue bottle deep v trust fund ramps. Portland mustache waistcoat tattooed, synth shoreditch fixie farm-to-table XOXO PBR&B. Fanny pack pop-up wayfarers, skateboard pabst twee polaroid selvage listicle. Fingerstache meggings ennui, fixie pork belly flannel migas four loko pickled PBR&B polaroid kickstarter kale chips waistcoat plaid.\r\n\r\nHelvetica microdosing truffaut pabst neutra. Mustache kale chips wolf pug, vinyl chambray meditation austin literally blue bottle fanny pack pour-over health goth godard beard. You probably haven't heard of them poutine venmo banjo, tattooed marfa craft beer microdosing bicycle rights locavore. Plaid bitters kombucha narwhal pabst hoodie. Cronut celiac chartreuse, DIY skateboard synth kickstarter tilde food truck salvia poutine dreamcatcher gastropub iPhone shabby chic. Plaid cred chia, deep v readymade neutra narwhal before they sold out church-key forage. Tofu messenger bag bespoke, tote bag gastropub echo park whatever ethical single-origin coffee street art.", question_author: "YOLO", question_title: "Helvetica microdosing truffaut pabst neutra?", section_id: 4},
  {question_content: "Keffiyeh try-hard chambray venmo tattooed ennui, drinking vinegar butcher mustache. Pop-up hoodie actually everyday carry heirloom.\r\n\r\nPoutine letterpress pour-over, you probably haven't heard of them knausgaard sriracha drinking vinegar lo-fi slow-carb tilde mustache. Knausgaard wolf chicharrones, chambray pug selvage listicle microdosing dreamcatcher you probably haven't heard of them keffiyeh 90's. 3 wolf moon letterpress meh VHS, tilde skateboard banh mi post-ironic cronut yr.\r\n\r\nOffal meditation street art, helvetica roof party bespoke affogato VHS migas marfa flexitarian next level intelligentsia tumblr. Pour-over vegan pinterest tacos, microdosing mumblecore aesthetic mixtape. Tattooed drinking vinegar flannel hashtag normcore lomo. Listicle keffiyeh celiac gastropub, drinking vinegar trust fund fanny pack. Waistcoat offal normcore, intelligentsia salvia green juice organic. Dreamcatcher street art iPhone beard. Blog polaroid tilde sartorial green juice crucifix.", question_author: "Knausgaard wolf ", question_title: "Poutine letterpress pour-over, you probably haven't heard of them.", section_id: 1}
])
